resources:
- resources/deployment.yaml
- resources/pvc.yaml
- resources/service.yaml

configMapGenerator:
- name: nginx-config
  files:
  - config/nginx.conf
- name: php-config
  files:
  - config/fpm.conf
