apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-data
          mountPath: /app
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
            ephemeral-storage: 100Mi
      - name: php
        image: gcr.io/hpd-io/docker-wordpress-php:7010eea3507911656367e1f511846e899bfa23c6
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: wordpress-data
          mountPath: /app
        - name: php-config
          mountPath: /usr/local/etc/php-fpm.d/zzzzz.conf
          subPath: fpm.conf
        resources:
          requests:
            cpu: 700m
            memory: 768Mi
            ephemeral-storage: 100Mi
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-pvc
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: php-config
        configMap:
          name: php-config
